name: Publish gem

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.0
    - name: Check if version changed
      uses: tony84727/changed-file-filter@0.0.2
      id: filter
      with:
        filters: |
          version:
            - 'lib/pier_logging/version.rb'
    - name: Setup Ruby
      if: steps.filter.outputs.version == 'true'
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Get version
      if: steps.filter.outputs.version == 'true'
      id: new_version
      run: echo "##[set-output name=version;]$(ruby ./bin/get_current_version.rb)"
    - name: Create tag
      if: steps.filter.outputs.version == 'true'
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "${{ steps.new_version.outputs.version }}"
    - name: Create Release
      if: steps.filter.outputs.version == 'true'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.new_version.outputs.version }}
        release_name: Release ${{ steps.new_version.outputs.version }}
        tag_prefix: v
        draft: false
        prerelease: false
    - name: Publish Gem
      if: steps.filter.outputs.version == 'true'
      env:
        VERSION: ${{ steps.new_version.outputs.version }}
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: ruby ./bin/publish_gem.rb
    - name: Notify deploy status to Slack
      if: steps.filter.outputs.version == 'true'
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        STATUS: ${{ job.status }}
        GH_MESSAGE: ${{ github.event.commits[0].message }}
        GH_ACTOR: ${{ github.actor }}
        GH_SHA: ${{ github.sha }}
        GH_REPO: ${{ github.repository }}
        APP_ENVIRONMENT: rubygems
        SLACK_CHANNEL: CEBAD7R0F
        LANGUAGE: "ruby" # "python", "nodejs" 
        DEPLOY_TARGET: ${{ github.event.repository.name }}
      run: /bin/bash ./bin/notify_slack_github.sh
