name: Publish gem

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.0
    - name: Check if version changed
      uses: tony84727/changed-file-filter@0.0.2
      id: filter
      with:
        filters: |
          version:
            - 'lib/pier_logging/version.rb'
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Publish Gem
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: /bin/bash ./bin/publish_gem.sh
